server:
  port: 8671
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: eureka-server
